baseURL = "https://coaxito.com/"
languageCode = "pt-br"
title = "Breno's Blog"

[params]
  description = "Breno's Blog é o cantinho digital aconchegante de Breno Santana, onde ele escreve sobre música, tecnologia, internet e outros tópicos pessoais."
  author = "Breno Santana"
  defaultOgImage = "/images/default-og-image.jpg"
  twitterUsername = "c0axit0"
  logo = "/images/logo.png"
