baseURL = "https://coaxito.com/"
languageCode = "pt-br"
title = "Coaxito's Café"

[params]
  description = "Coaxito's Café é o cantinho digital aconchegante de Breno Santana (@c0axit0), onde ele escreve sobre música, tecnologia, internet e outros tópicos pessoais."
  author = "Breno Santana"
  defaultOgImage = "/images/default-og-image.jpg"
  twitterUsername = "c0axit0"
  logo = "/images/logo.png"
